-- AJUSTES PERMISOS Y ROLES
alter table roles add column modulo_ini varchar(255) not null;
alter table roles add column cod varchar(3) not null;
delete from permissions;
alter table permissions drop column alias;
alter table permissions drop column status;
alter table permissions add column grupo varchar(255) not null;
alter table permissions add column obs varchar(255);

insert into permissions values(1,'variables','web',now(),now(), 'variables', 'Permite ingresar al menú de "Variables"');
insert into permissions values(2,'variable_ingresar',  'web',now(),now(),'variable_ingresar', 'Permite ingresar a la opción "Variables > Ingresar"');
insert into permissions values(3,'variable_ingresar_editar','web',now(),now(),'variable_ingresar', 'Permite acciones de edición en la opción "Variables > Ingresar"');
insert into permissions values(4,'variable_habilitar','web',now(),now(),'variable_habilitar', 'Permite ingresar a la opción "Variables > Habilitar"');
insert into permissions values(5,'metas','web',now(),now(),'metas', 'Permite ingresar al menú de "Metas"');
insert into permissions values(6,'metas_editar','web',now(),now(),'metas', 'Permite acciones de edición en el menú "Metas"');
insert into permissions values(7,'config','web',now(),now(),'config', 'Permite ingresar al menú de "Configuración"');
insert into permissions values(8,'config_variables','web',now(),now(),'config_variables', 'Permite ingresar a la opción "Configuración > Variables"');
insert into permissions values(9,'config_variables_editar','web',now(),now(),'config_variables', 'Permite acciones de edición en la opción "Configuración > Variables"');
insert into permissions values(10,'config_indicadores','web',now(),now(),'config_indicadores', 'Permite ingresar a la opción "Configuración > Indicadores"');
insert into permissions values(11,'config_indicadores_editar','web',now(),now(),'config_indicadores', 'Permite acciones de edición en la opción "Configuración > Indicadores"');
insert into permissions values(12,'areas','web',now(),now(),'areas', 'Permite ingresar a la opción "Configuración > Áreas"');
insert into permissions values(13,'areas_editar','web',now(),now(),'areas', 'Permite acciones de edición en la opción "Configuración > Áreas"');
insert into permissions values(14,'categorias','web',now(),now(),'categorias', 'Permite ingresar a la opción "Configuración > Categorías"');
insert into permissions values(15,'categorias_editar','web',now(),now(),'categorias', 'Permite acciones de edición en la opción "Configuración > Categorías"');
insert into permissions values(16,'subcategorias_editar','web',now(),now(),'subcategorias','Permite ingresar a la opción "Configuración > Subcategorías"');
insert into permissions values(17,'subcategorias','web',now(),now(),'subcategorias','Permite acciones de edición en la opción "Configuración > Subcategorías"');
insert into permissions values(18,'seguridad','web',now(),now(),'seguridad', 'Permite ingresar al menú de "Seguridad"');
insert into permissions values(19,'roles','web',now(),now(),'roles','Permite ingresar a la opción "Seguridad > Role"');
insert into permissions values(20,'usuarios','web',now(),now(),'usuarios','Permite ingresar a la opción "Seguridad > Permisos"');
insert into permissions values(21,'permisos','web',now(),now(),'permisos','Permite ingresar a la opción "Seguridad > Usuarios"');
insert into permissions values(22,'dashboard','web',now(),now(),'dashboard', 'Permite ingresar al menú de "Dashboard"');
insert into permissions values(23,'indicador_analisis','web',now(),now(),'indicador_analisis','Permite ingresar al menú de "Análisis de Indicadores"');
insert into permissions values(24,'indicador_analisis_editar','web',now(),now(),'indicador_analisis', 'Permite acciones de edición en menú "Análisis de Indicadores"');
insert into permissions values(25,'metas_habilitar','web',now(),now(),'metas', 'Permite habilitar o deshabilitar el ingreso de metas');

update roles set name = 'Administrador', guard_name = 'web', modulo_ini = 'analysis', cod = 'ADM' where id=1;
update roles set name = 'Colaborador', guard_name = 'web', modulo_ini = 'setvariable', cod = 'COL' where id=2;
update roles set name = 'Auditor', guard_name = 'web', modulo_ini = 'analysis', cod = 'AUD' where id=5;
update roles set name = 'Jefe de Area', guard_name = 'web', modulo_ini = 'analysis', cod = 'JEF' where id=6;

-- administrador
insert into role_has_permissions values(1,1);
insert into role_has_permissions values(2,1);
insert into role_has_permissions values(3,1);
insert into role_has_permissions values(4,1);
insert into role_has_permissions values(5,1);
insert into role_has_permissions values(6,1);
insert into role_has_permissions values(7,1);
insert into role_has_permissions values(8,1);
insert into role_has_permissions values(9,1);
insert into role_has_permissions values(10,1);
insert into role_has_permissions values(11,1);
insert into role_has_permissions values(12,1);
insert into role_has_permissions values(13,1);
insert into role_has_permissions values(14,1);
insert into role_has_permissions values(15,1);
insert into role_has_permissions values(16,1);
insert into role_has_permissions values(17,1);
insert into role_has_permissions values(18,1);
insert into role_has_permissions values(19,1);
insert into role_has_permissions values(20,1);
insert into role_has_permissions values(21,1);
insert into role_has_permissions values(22,1);
insert into role_has_permissions values(23,1);
insert into role_has_permissions values(24,1);
insert into role_has_permissions values(25,1);
-- colaborador
insert into role_has_permissions values(1,2);
insert into role_has_permissions values(2,2);
insert into role_has_permissions values(3,2);
insert into role_has_permissions values(5,2);
insert into role_has_permissions values(6,2);
insert into role_has_permissions values(23,2);
insert into role_has_permissions values(24,2);
-- Auditor
insert into role_has_permissions values(1,5);
insert into role_has_permissions values(2,5);
insert into role_has_permissions values(5,5);
insert into role_has_permissions values(7,5);
insert into role_has_permissions values(8,5);
insert into role_has_permissions values(10,5);
insert into role_has_permissions values(12,5);
insert into role_has_permissions values(14,5);
insert into role_has_permissions values(16,5);
insert into role_has_permissions values(22,5);
insert into role_has_permissions values(23,5);
-- Jefe de área
insert into role_has_permissions values(1,6);
insert into role_has_permissions values(2,6);
insert into role_has_permissions values(5,6);
insert into role_has_permissions values(7,6);
insert into role_has_permissions values(8,6);
insert into role_has_permissions values(10,6);
insert into role_has_permissions values(12,6);
insert into role_has_permissions values(14,6);
insert into role_has_permissions values(16,6);
insert into role_has_permissions values(22,6);
insert into role_has_permissions values(23,6);

insert into model_has_roles values (1,'App\\Models\\User', 3);
insert into model_has_roles values (1,'App\\Models\\User', 1);
insert into model_has_roles values (1,'App\\Models\\User', 4);
insert into model_has_roles values (2,'App\\Models\\User',30);
insert into model_has_roles values (2,'App\\Models\\User',21);
insert into model_has_roles values (2,'App\\Models\\User',23);
insert into model_has_roles values (2,'App\\Models\\User',24);
insert into model_has_roles values (2,'App\\Models\\User',25);
insert into model_has_roles values (2,'App\\Models\\User',26);
insert into model_has_roles values (2,'App\\Models\\User',27);
insert into model_has_roles values (2,'App\\Models\\User',28);
insert into model_has_roles values (2,'App\\Models\\User',29);
insert into model_has_roles values (2,'App\\Models\\User',31);
insert into model_has_roles values (2,'App\\Models\\User',32);
insert into model_has_roles values (2,'App\\Models\\User',33);
insert into model_has_roles values (2,'App\\Models\\User',34);
insert into model_has_roles values (2,'App\\Models\\User',35);
insert into model_has_roles values (2,'App\\Models\\User',36);
insert into model_has_roles values (2,'App\\Models\\User',37);
insert into model_has_roles values (2,'App\\Models\\User',38);
insert into model_has_roles values (2,'App\\Models\\User',20);
insert into model_has_roles values (2,'App\\Models\\User', 5);
insert into model_has_roles values (2,'App\\Models\\User',10);
insert into model_has_roles values (2,'App\\Models\\User',11);
insert into model_has_roles values (2,'App\\Models\\User',12);
insert into model_has_roles values (2,'App\\Models\\User',13);
insert into model_has_roles values (2,'App\\Models\\User',14);
insert into model_has_roles values (2,'App\\Models\\User',15);
insert into model_has_roles values (2,'App\\Models\\User',16);
insert into model_has_roles values (2,'App\\Models\\User',17);
insert into model_has_roles values (2,'App\\Models\\User',19);
insert into model_has_roles values (2,'App\\Models\\User',22);
insert into model_has_roles values (5,'App\\Models\\User', 7);
insert into model_has_roles values (5,'App\\Models\\User', 6);
insert into model_has_roles values (6,'App\\Models\\User',18);
insert into model_has_roles values (6,'App\\Models\\User', 9);
insert into model_has_roles values (6,'App\\Models\\User', 8);
insert into model_has_roles values (6,'App\\Models\\User',39);
