insert into aux_periodo_dets values (null,1,7,1,'jul',2);
insert into aux_periodo_dets values (null,1,8,1,'ago',2);
insert into aux_periodo_dets values (null,1,9,1,'sep',2);
insert into aux_periodo_dets values (null,1,10,1,'oct',2);
insert into aux_periodo_dets values (null,1,11,1,'nov',2);
insert into aux_periodo_dets values (null,1,12,1,'dic',2);
insert into aux_periodo_dets values (null,1,1,1,'ene',2);
insert into aux_periodo_dets values (null,1,2,1,'feb',2);
insert into aux_periodo_dets values (null,1,3,1,'mar',2);
insert into aux_periodo_dets values (null,1,4,1,'abr',2);
insert into aux_periodo_dets values (null,1,5,1,'may',2);
insert into aux_periodo_dets values (null,1,6,1,'jun',2);
insert into aux_periodo_dets values (null,2,7,0,NULL,2);
insert into aux_periodo_dets values (null,2,8,1,'jul-ago',2);
insert into aux_periodo_dets values (null,2,9,0,NULL,2);
insert into aux_periodo_dets values (null,2,10,1,'sep-oct',2);
insert into aux_periodo_dets values (null,2,11,0,NULL,2);
insert into aux_periodo_dets values (null,2,12,1,'nov-dic',2);
insert into aux_periodo_dets values (null,2,1,0,NULL,2);
insert into aux_periodo_dets values (null,2,2,1,'ene-feb',2);
insert into aux_periodo_dets values (null,2,3,0,NULL,2);
insert into aux_periodo_dets values (null,2,4,1,'mar-abr',2);
insert into aux_periodo_dets values (null,2,5,0,NULL,2);
insert into aux_periodo_dets values (null,2,6,1,'may-jun',2);
insert into aux_periodo_dets values (null,3,7,0,NULL,2);
insert into aux_periodo_dets values (null,3,8,0,NULL,2);
insert into aux_periodo_dets values (null,3,9,1,'trim 1',2);
insert into aux_periodo_dets values (null,3,10,0,NULL,2);
insert into aux_periodo_dets values (null,3,11,0,NULL,2);
insert into aux_periodo_dets values (null,3,12,1,'trim 2',2);
insert into aux_periodo_dets values (null,3,1,0,NULL,2);
insert into aux_periodo_dets values (null,3,2,0,NULL,2);
insert into aux_periodo_dets values (null,3,3,1,'trim 3',2);
insert into aux_periodo_dets values (null,3,4,0,NULL,2);
insert into aux_periodo_dets values (null,3,5,0,NULL,2);
insert into aux_periodo_dets values (null,3,6,1,'trim 4',2);
insert into aux_periodo_dets values (null,4,7,0,NULL,2);
insert into aux_periodo_dets values (null,4,8,0,NULL,2);
insert into aux_periodo_dets values (null,4,9,0,NULL,2);
insert into aux_periodo_dets values (null,4,10,0,NULL,2);
insert into aux_periodo_dets values (null,4,11,0,NULL,2);
insert into aux_periodo_dets values (null,4,12,1,'sem 1',2);
insert into aux_periodo_dets values (null,4,1,0,NULL,2);
insert into aux_periodo_dets values (null,4,2,0,NULL,2);
insert into aux_periodo_dets values (null,4,3,0,NULL,2);
insert into aux_periodo_dets values (null,4,4,0,NULL,2);
insert into aux_periodo_dets values (null,4,5,0,NULL,2);
insert into aux_periodo_dets values (null,4,6,1,'sem 2',2);
insert into aux_periodo_dets values (null,5,7,0,NULL,2);
insert into aux_periodo_dets values (null,5,8,0,NULL,2);
insert into aux_periodo_dets values (null,5,9,0,NULL,2);
insert into aux_periodo_dets values (null,5,10,0,NULL,2);
insert into aux_periodo_dets values (null,5,11,0,NULL,2);
insert into aux_periodo_dets values (null,5,12,0,NULL,2);
insert into aux_periodo_dets values (null,5,1,0,NULL,2);
insert into aux_periodo_dets values (null,5,2,0,NULL,2);
insert into aux_periodo_dets values (null,5,3,0,NULL,2);
insert into aux_periodo_dets values (null,5,4,0,NULL,2);
insert into aux_periodo_dets values (null,5,5,0,NULL,2);
insert into aux_periodo_dets values (null,5,6,1,'Año',2);